### ISSUE TITLE
About the probe classifier

### ISSUE THREAD

**Issue by Punchwes** [aetting/compeval#1]
Hi @aetting , I am very grateful for the released code and your paper is extremely interesting.
https://github.com/aetting/compeval/blob/0cd88a6dee004633d4decfa5b80fd64f0c30dbc3/xy_classify.py#L157
When looking into your code, it seems that the classifier you used above does not match your description in your paper where you said a MLP with a single hidden layer. It seems to be the same case for hyperparameters, you use the default parameters for MLP other than suggested by Adi et al. (2016). I wonder if it is because that the code in this repo is not the latest version?

**Comment by aetting** [comment]
Hi @Punchwes, thank you for your comment. You are correct -- this is not the version of the code that was used for the results reported in the paper (this version reflects additional experiments run later on, and included in my dissertation). What you've found here is a repository that was not linked in the paper, and wasn't actually intended for public use (carelessly I left it here, which I see now has caused confusion). With the paper itself, I actually only released the code for the generation system, and never ended up releasing the classification code for public use. If there is demand, I could also clean up and release the classification code.

**Comment by Punchwes** [comment]
Hi @aetting, thanks very much for your reply. Oh I see the point, it would be great and I appreciate it so much if you could release the code which could minimise the unclearness to reproduce your results :).

**Comment by aetting** [comment]
I've now added classifier code to the provided probing datasets at https://aetting.github.io/compeval.html -- the code there should reflect the experimental settings reported in the paper, but let me know if you encounter further issues.
